### ISSUE TITLE
dodat nucené braní figurek

### ISSUE THREAD

**Issue by Libor03** [Adyxx/rocnikovy_projekt#13]

**Comment by Libor03** [comment]
problém s indexy, možnost zvětšit na 10 dimenzí a vykreslit jenom 8, ať můžeme kontrolovat, potřebuji pomoct s tím ifem

**Comment by Libor03** [comment]
základní if napsát, potřeba dopsat, aby bralo v potaz barvy a nebralo v potaz políčka, které neexistují

**Comment by Adyxx** [comment]
fixed

**Comment by Libor03** [comment]
nekontrolovat figurky barvy, které nejsou na tahu

**Comment by Libor03** [comment]
snad hotovo
